language: python
python:
  - '3.7'

install:
  - pip install --upgrade pip
  - pip install --upgrade setuptools
  - pip install -e ".[tf,test]" --progress-bar off

script:
  - pytest tests --cov=spellnn
